# Generated by Django 3.1.2 on 2020-11-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_pricelookupevent_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='one_off_scrape',
            field=models.BooleanField(default=False),
        ),
    ]
