# Generated by Django 3.1.2 on 2020-11-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_company_one_off_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_granular_scraping',
            field=models.BooleanField(default=False),
        ),
    ]
