# Generated by Django 3.1.2 on 2020-11-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_company_periodic_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='periodic_task',
        ),
    ]
