# Generated by Django 3.1.2 on 2020-11-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_company_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='scraping_scheduler_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
